### ISSUE TITLE
Images overflow on iOS Version 17.4.1

### ISSUE THREAD

**Issue by mirhamasala** [FilecoinFoundationWeb/filecoin-foundation#211]
![7C5A5A09-2A80-41DC-9FA0-54DC38FBF78A_1_105_c](https://github.com/FilecoinFoundationWeb/filecoin-foundation/assets/26620750/aa6e9c0a-0ddc-45a4-9456-042a9cff889b)

**Comment by CharlyMartin** [comment]
Fixed as part of https://github.com/FilecoinFoundationWeb/filecoin-foundation/pull/235
