### ISSUE TITLE
www.fil.org errors out, does not redirect to fil.org

### ISSUE THREAD

**Issue by dannyob** [FilecoinFoundationWeb/filecoin-foundation#223]
Expected: typing https://www.fil.org/ should take me to the Filecoin Foundation home page
What I got: 
<img width="690" alt="image" src="https://github.com/FilecoinFoundationWeb/filecoin-foundation/assets/227660/4e438fa6-393a-4629-872a-72ad0dfe8b16">

**Comment by mirhamasala** [comment]
Thank you again for reporting, @dannyob. This issue has now been fixed. 💙
