### ISSUE TITLE
Look into "react/jsx-sort-props”

### ISSUE THREAD

**Issue by mirhamasala** [FilecoinFoundationWeb/filecoin-foundation#62]
I don’t remember exactly anymore but I believe after installing some Tailwind plugin (the one that checks the order of the classes perhaps?), `react/jsx-sort-props` stopped working.

Config file is at `.eslintrc.json`

```
    "react/jsx-sort-props": [
      "error",
      {
        "callbacksLast": true,
        "shorthandFirst": true,
        "noSortAlphabetically": true,
        "reservedFirst": true
      }
    ],
```

Could also have a look at  best practices on the sort order once working again.

**Comment by barbaraperic** [comment]
@mirhamasala if I run `npm run lint` it reorders the props - see example below with adding `onClick` prop to `Badge` component. Is it expected to work in a different way? 

https://github.com/FilecoinFoundationWeb/filecoin-foundation/assets/50910606/5c60ea59-5bbb-44af-ad22-661193fa4a93

**Comment by mirhamasala** [comment]
>@mirhamasala if I run npm run lint it reorders the props - see example below with adding onClick prop to Badge component. Is it expected to work in a different way?

@barbaraperic Nope, you're right. It works. I do think we might want to extend it. To something like:

```
    "react/jsx-sort-props": [
      "error",
      {
        "callbacksLast": true,
        "multiline": "last",
        "noSortAlphabetically": false,
        "reservedFirst": true,
        "shorthandFirst": true
      }
    ],
```    

 Let's discuss with @CharlyMartin.
